version: "2"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters:
  enable:
    - govet
    - errcheck
    - bodyclose
    - misspell
    - staticcheck
    - unused
    - ineffassign
    - unparam
    - dupl
    - nestif
    - revive
    - testpackage
    - thelper
  exclusions:
    rules:
      - path: '(.+)_test\.go$'
        linters:
          - errcheck
  settings:
    revive:
      enable-all-rules: true
      rules:
        - name: package-comments
          disabled: true
        - name: add-constant
          disabled: true
        - name: var-naming
          disabled: true
        - name: line-length-limit
          arguments: [120]
        - name: function-length
          arguments: [100, 0]
        - name: file-length-limit
          arguments:
            - max: 1000
              skip-comments: false
              skip-blank-lines: false
        - name: unhandled-error
          exclude: ["**/*_test.go"]
    nestif:
      min-complexity: 4

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
